version: '2'

services:

  postgresql:
    container_name:
      posgres
    image: 'docker.io/bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=my_database
    networks:
      - pgtapper

  pgtaptest:
    container_name:
      pgtap
    image: 'subzerocloud/pgtap:pg13'
    ports:
      - '5432:5432'
    volumes:
        - "./tests:/test"
    environment:
      - HOST=posgres
      - USER=my_user
      - PASSWORD=password123
      - DATABASE=my_database
    networks:
      - pgtapper

volumes:
  postgresql_data:
    driver: local

networks:
  pgtapper:
    driver: bridge
